
[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=980362F1C140DBE0F1DECD8626117538

[/Script/EngineSettings.GameMapsSettings]
; GameInstance Class for autodetection GPU
GameInstanceClass=/Script/UE_IoroomProject.IoroomGameInstance
GlobalDefaultGameMode=/Script/UE_IoroomProject.IoroomGameMode
GameDefaultMap=/Engine/Maps/Templates/OpenWorld
